// presets.js
export const presets = {
  main: [
    { label: 'Username', field: 'username_cc' },
    { label: 'Rank', field: 'rank' },
    { label: 'Equipped Avatar', field: 'equipped_avatar' },
    { label: 'Login Streak', field: 'daily_login_streak' },
    {
      label: 'Longest Login Streak',
      field: 'longest_daily_login_streak',
    },
    { label: 'Equipped Hub Title', field: 'equipped_hub_title' },
    { label: 'Hub Titles Count', field: 'hub_title_count' },
    { label: 'Avatar Count', field: 'avatar_count' },
    { label: 'Costume Count', field: 'costume_count' },
    { label: 'Hat Count', field: 'hat_count' },
    { label: 'Backbling Count', field: 'backbling_count' },
    { label: 'Friend Count', field: 'friend_count' },
    { label: 'Quest Count', field: 'quest_count' },
  ],
  bed: [
    { label: 'XP', field: 'xp' },
    { label: 'Games Played', field: 'played' },
    { label: 'Wins', field: 'victories' },
    { label: 'Kills', field: 'kills' },
    { label: 'Deaths', field: 'deaths' },
    { label: 'Final Kills', field: 'final_kills' },
    { label: 'Beds Destroyed', field: 'beds_destroyed' },
  ],
  sky: [
    { label: 'XP', field: 'xp' },
    { label: 'Games Played', field: 'played' },
    { label: 'Wins', field: 'victories' },
    { label: 'Kills', field: 'kills' },
    { label: 'Deaths', field: 'deaths' },
    { label: 'Mystery Chests Destroyed', field: 'mystery_chests_destroyed' },
    { label: 'Ores Mined', field: 'ores_mined' },
    { label: 'Spells Used', field: 'spells_used' },
  ],
  dr: [
    { label: 'XP', field: 'xp' },
    { label: 'Games Played', field: 'played' },
    { label: 'Wins', field: 'victories' },
    { label: 'Kills', field: 'kills' },
    { label: 'Deaths', field: 'deaths' },
    { label: 'Checkpoints', field: 'checkpoints' },
    { label: 'Activated Traps', field: 'activated' },
  ],
  wars: [
    { label: 'XP', field: 'xp' },
    { label: 'Games Played', field: 'played' },
    { label: 'Wins', field: 'victories' },
    { label: 'Kills', field: 'kills' },
    { label: 'Deaths', field: 'deaths' },
    { label: 'Final Kills', field: 'final_kills' },
    { label: 'Treasures Destroyed', field: 'treasure_destroyed' },
  ],
  murder: [
    { label: 'XP', field: 'xp' },
    { label: 'Games Played', field: 'played' },
    { label: 'Wins', field: 'victories' },
    { label: 'Kills', field: 'kills' },
    { label: 'Deaths', field: 'deaths' },
    { label: 'Coins', field: 'coins' },
    { label: 'Murders', field: 'murders' },
    { label: 'Murderer Eliminations', field: 'murderer_eliminations' },
  ],
  party: [
    { label: 'XP', field: 'xp' },
    { label: 'Games Played', field: 'played' },
    { label: 'Wins', field: 'victories' },
    { label: 'Powerups Collected', field: 'powerups_collected' },
    { label: 'Rounds Survived', field: 'rounds_survived' },
  ],
  ground: [
    { label: 'XP', field: 'xp' },
    { label: 'Games Played', field: 'played' },
    { label: 'Blocks Destroyed', field: 'blocks_destroyed' },
    { label: 'Blocks Placed', field: 'blocks_placed' },
    { label: 'Deaths', field: 'deaths' },
    { label: 'Kills', field: 'kills' },
    { label: 'Projectiles Fired', field: 'projectiles_fired' },
  ],
};
